variable "AWS_ACCESS_KEY_ID" {
  type    = string
  default = "${env("AWS_ACCESS_KEY_ID")}"
}

variable "AWS_SECRET_ACCESS_KEY" {
  type    = string
  default = "${env("AWS_SECRET_ACCESS_KEY")}"
}

packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.AWS_ACCESS_KEY_ID}"
  filters = {
    name                = "ubuntu/images/*ubuntu-jammy-22.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-1"
  secret_key  = "${var.AWS_SECRET_ACCESS_KEY}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  profile       = "dev"
  access_key = var.AWS_ACCESS_KEY_ID
  secret_key = var.AWS_SECRET_ACCESS_KEY
  source_ami    = "ami-013b3de8a8fa9b39f"
  ssh_keypair_name = "dev"
  ssh_private_key_file = "/home/ruby/Downloads/dev.pem"
  ami_name      = "app-image-${local.timestamp}"
  instance_type = "t2.micro"
  region        = "us-east-1"
  ssh_username  = "ubuntu"
  vpc_id        = "vpc-0acefcad24c0b914b"
  subnet_id     = "subnet-02d41e81eddf16052"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "../scripts/setup.sh"
  }

  provisioner "shell" {
    script = "../scripts/install-database.sh"
  }

}
