name: Build and Share AMI

on:
  pull_request_target:
    branches:
      - main

jobs:
  build_and_share_ami:
    name: Build and Share AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Packer
        run: |
          cd packer/templates
          packer init .

      - name: Build AMI
        run: |
          cd packer/templates
          packer build myapp-template.pkr.hcl
          
      - name: Retrieve and Share AMI
        run: |
          echo "Retrieving AMI ID..."
          AMI_ID=$(aws ec2 describe-images --filters "Name=name,Values=your-ami-name" --query "Images[0].ImageId" --output text)
          echo "AMI ID: $AMI_ID"
          echo "Modifying AMI launch permissions..."
          aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId='703671935232'}]"
          echo "Permissions modified for AMI ID $AMI_ID"