name: Packer Template Validation

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Application Artifact
        run: |
          mkdir artifacts
          zip -r artifacts/webapp.zip .

      - name: Install Packer
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install packer

      - name: Initialize Packer
        run: packer init myapp-template.pkr.hcl

      - name: Validate Packer Template
        run: packer validate myapp-template.pkr.hcl

      - name: Check Packer Template Formatting
        run: |
          if ! packer fmt -check myapp-template.pkr.hcl; then
            echo "Packer template is not formatted correctly. Please format using 'packer fmt' and re-push."
            exit 1
          fi
